### ISSUE TITLE
Uncaught TypeError: Cannot read property 'href' of undefined

### ISSUE THREAD

**Issue by Kapu06** [atom/autocomplete-html#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.4.16
**OS**: linux 4.10.13-1-ARCH
**Thrown From**: [autocomplete-html](https://github.com/atom/autocomplete-html) package 0.7.2

### Stack Trace

Uncaught TypeError: Cannot read property 'href' of undefined

```
At /usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:252

TypeError: Cannot read property 'href' of undefined
    at Object.getAttributeValues (/usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:252:46)
    at Object.getAttributeValueCompletions (/usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:192:21)
    at Object.getSuggestions (/usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:24:21)
    at /usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
> Electron: 1.4.16

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by Kapu06** [comment]
Ok, thanks =)
