### ISSUE TITLE
Failed to activate the autocomplete-html package

### ISSUE THREAD

**Issue by agungribowo** [atom/autocomplete-html#69]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [autocomplete-html](https://github.com/atom/autocomplete-html) package 0.7.3

### Stack Trace

Failed to activate the autocomplete-html package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:1)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:1)
    at requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/main.js:110:1)
    at Object.requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/main.js:31:1)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/main.js:107:1)
    at Object.consumeProvider_2_0 (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/main.js:86:1)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/service-hub/lib/service-hub.js:30:1)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:446:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:256:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:374:1
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.17.0/resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.17.0/resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.17.0/resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:185:1)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/settings-view/lib/package-card.js:361:1)
```

### Commands

```
     -6:10.5.0 core:undo (input.hidden-input)
     -6:06.9.0 autocomplete-plus:confirm (input.hidden-input)
  3x -6:03.8.0 core:backspace (input.hidden-input)
     -5:47.2.0 command-palette:toggle (input.hidden-input)
     -5:33.4.0 spell-check:toggle (input.hidden-input)
     -5:24.4.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
  3x -5:17.1.0 core:backspace (input.hidden-input)
     -5:14.5.0 autocomplete-plus:confirm (input.hidden-input)
  7x -5:12.3.0 core:undo (input.hidden-input)
  4x -5:08.0 core:backspace (input.hidden-input)
     -4:06.9.0 autocomplete-plus:activate (input.hidden-input)
     -4:04.2.0 core:backspace (input.hidden-input)
     -4:01.2.0 autocomplete-plus:activate (input.hidden-input)
     -3:59.5.0 core:backspace (input.hidden-input)
  2x -3:02.6.0 window:toggle-menu-bar (input.hidden-input)
     -2:04.0 grammar-selector:show (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report! Can you confirm a couple of things for us?

what were you doing at the time of the error?
is the error is reproducible?

**Comment by rsese** [comment]
Going to go ahead and close this in favor of https://github.com/atom/autocomplete-plus/issues/851.    If you're able to share steps to reproduce @agungribowo, please let us know in the issue :v:

**Comment by pappu789** [comment]
sir how i fix this problem on my atom editor

**Comment by jonathanpecany** [comment]
I need a fix as well. It will not work whatsoever.
